[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Laurent Leconte <laurent@lau.rent>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aws-lambda-typing = "^2.16.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
